import { h } from "vue";
import type { FieldSnapshot } from "@stages/core";
import type { VueFieldProps, VueFieldView } from "@stages/vue";
import { createEventLaunchFields, type BaseFieldProps, type CheckboxFieldProps, type ChoiceFieldProps, type MoneyFieldProps, type NumberFieldProps, type TextFieldProps } from "../../shared/event-launch/index.js";

function issues(id: string, field: FieldSnapshot) {
  return field.state.visibleIssues.length === 0 ? undefined : h("ul", { id: `${id}-issues`, class: "field-issues", role: field.state.visibleIssues.some((entry) => entry.severity === "error") ? "alert" : "status" }, field.state.visibleIssues.map((entry) => h("li", { key: entry.id }, entry.message ?? entry.code)));
}
function description(id: string, value?: string) { return value === undefined ? undefined : h("p", { id: `${id}-description`, class: "field-description" }, value); }
function label(id: string, props: BaseFieldProps) { return h("label", { for: id }, [props.label, props.required === true ? h("span", { class: "required", "aria-hidden": "true" }, " *") : undefined]); }
function inputA11y(id: string, field: FieldSnapshot, text?: string) {
  const invalid = field.state.visibleIssues.some((entry) => entry.severity === "error");
  return { "aria-invalid": invalid || undefined, "aria-describedby": [text === undefined ? undefined : `${id}-description`, field.state.visibleIssues.length > 0 ? `${id}-issues` : undefined].filter(Boolean).join(" ") || undefined };
}

const TextField: VueFieldView<string, TextFieldProps> = (binding: VueFieldProps<string, TextFieldProps>) => h("div", { class: "field" }, [label(binding.id, binding.props), h("input", { id: binding.id, type: binding.props.inputType ?? "text", value: binding.field.value, placeholder: binding.props.placeholder, disabled: binding.field.state.disabled, required: binding.props.required, ...inputA11y(binding.id, binding.field, binding.props.description), onInput: (event: Event) => binding.emit("input", (event.currentTarget as HTMLInputElement).value), onFocus: () => binding.emit("focus"), onBlur: () => binding.emit("blur") }), description(binding.id, binding.props.description), issues(binding.id, binding.field)]);
const TextareaField: VueFieldView<string, BaseFieldProps> = (binding: VueFieldProps<string, BaseFieldProps>) => h("div", { class: "field span-2" }, [label(binding.id, binding.props), h("textarea", { id: binding.id, value: binding.field.value, placeholder: binding.props.placeholder, disabled: binding.field.state.disabled, required: binding.props.required, ...inputA11y(binding.id, binding.field, binding.props.description), onInput: (event: Event) => binding.emit("input", (event.currentTarget as HTMLTextAreaElement).value), onFocus: () => binding.emit("focus"), onBlur: () => binding.emit("blur") }), description(binding.id, binding.props.description), issues(binding.id, binding.field)]);
const ChoiceField: VueFieldView<string, ChoiceFieldProps> = (binding: VueFieldProps<string, ChoiceFieldProps>) => h("div", { class: "field" }, [h("fieldset", { class: "choice-field", disabled: binding.field.state.disabled }, [h("legend", [binding.props.label, binding.props.required === true ? h("span", { class: "required" }, " *") : undefined]), h("div", { class: "choice-options" }, binding.props.options.map((option) => h("label", { key: option.value }, [h("input", { type: "radio", name: binding.id, value: option.value, checked: binding.field.value === option.value, onChange: () => binding.emit("input", option.value), onFocus: () => binding.emit("focus"), onBlur: () => binding.emit("blur") }), option.label])))]), description(binding.id, binding.props.description), issues(binding.id, binding.field)]);
function numeric(binding: VueFieldProps<number | undefined, NumberFieldProps | MoneyFieldProps>) { return h("div", { class: "field" }, [label(binding.id, binding.props), h("div", { class: "number-wrap" }, [h("input", { id: binding.id, type: "number", value: binding.field.value ?? "", min: binding.props.min, max: binding.props.max, step: binding.props.step, disabled: binding.field.state.disabled, ...inputA11y(binding.id, binding.field, binding.props.description), onInput: (event: Event) => { const input = event.currentTarget as HTMLInputElement; binding.emit("input", input.value === "" ? undefined : input.valueAsNumber); }, onFocus: () => binding.emit("focus"), onBlur: () => binding.emit("blur") }), h("span", "currency" in binding.props ? binding.props.currency : binding.props.suffix)]), description(binding.id, binding.props.description), issues(binding.id, binding.field)]); }
const NumberField: VueFieldView<number | undefined, NumberFieldProps> = numeric;
const MoneyField: VueFieldView<number | undefined, MoneyFieldProps> = numeric;
const CheckboxField: VueFieldView<boolean, CheckboxFieldProps> = (binding: VueFieldProps<boolean, CheckboxFieldProps>) => h("div", { class: "field span-2" }, [h("label", { class: "checkbox-label", for: binding.id }, [h("input", { id: binding.id, type: "checkbox", checked: binding.field.value, disabled: binding.field.state.disabled, onChange: (event: Event) => binding.emit("input", (event.currentTarget as HTMLInputElement).checked), onFocus: () => binding.emit("focus"), onBlur: () => binding.emit("blur") }), binding.props.label]), description(binding.id, binding.props.description), issues(binding.id, binding.field)]);

export const eventLaunchVueFields = createEventLaunchFields({ text: TextField, textarea: TextareaField, choice: ChoiceField, number: NumberField, money: MoneyField, checkbox: CheckboxField });
